server:
  port: 9000

spring:
  application:
    name: team8

  datasource:
    url: jdbc:mysql://database-1.c5svq8o9wqfm.ap-northeast-2.rds.amazonaws.com/ecommerce
    username: test
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
